### ISSUE TITLE
paste button needs to move when image is loaded

### ISSUE THREAD

**Issue by AndrewTG5** [andrewthegreat5/ImageConverterJava#11]
it can't be hidden because the user won't be able to paste once an image is loaded

**Comment by AndrewTG5** [comment]
@Matchlesmage0 what do you think is better? or can you think of a better place?
![image](https://user-images.githubusercontent.com/43556463/88239306-242aac00-ccd8-11ea-99bf-d038964c29b3.png)
![image](https://user-images.githubusercontent.com/43556463/88239322-3573b880-ccd8-11ea-8173-33c94061366b.png)
should the buttons always be in those positions or only when an image is loaded?

**Comment by ZManning7** [comment]
The second option seems neater but it could block the preview so i would go with the first option
