### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by AndrewTG5** [andrewthegreat5/ImageConverterJava#13]
![new icon](https://user-images.githubusercontent.com/43556463/89134268-e7806f80-d577-11ea-9580-4a27757359f7.png)
![icon](https://user-images.githubusercontent.com/43556463/89134270-e94a3300-d577-11ea-8407-3d074c7628c7.png)
Which is better the current one or the new one. And why.

**Comment by ZManning7** [comment]
I like the second one because it is unique and does not look like an adobe product your program would best stay with the bottom image
