### ISSUE TITLE
Need file navigation for import

### ISSUE THREAD

**Issue by ZManning7** [andrewthegreat5/ImageConverterJava#2]
As well as drag and drop a "select file" is necessary for people who do not prefer to or have enough screen space to easily drag and drop

**Comment by ZManning7** [comment]
Also a batch file conversion option would be nice

**Comment by ZManning7** [comment]
One other thing is that a small X to remove the current image would make life easier

**Comment by AndrewTG5** [comment]
please make new issues for the other comments
